### ISSUE TITLE
Script Showing in Player UI

### ISSUE THREAD

**Issue by RogueCalzone** [jalensailin/bottlecap#1]
![photo_2023-10-26_13-14-42](https://github.com/jalensailin/bottlecap/assets/149108430/f748b45c-57a0-4687-821b-6729a6e2dea4)

Hi Jalen! First off, wanted to say thanks for your work on this module. It's running flawlessly for my Pathfinder 1e group so far.

The only issue I've noticed is a little UI problem. Next to where the bottlecap/cog image is on the Players tab, I'm seeing script that says 'data-tooltip-direction="UP">0'. I assume that's part of a conditional statement to show the cog. Obviously it's not showing on any of your previews for the module, and I can't figure out how to make the text go away. Any help you could offer would be appreciated!

**Comment by jalensailin** [comment]
My apologies! I will look into this. First off, are there any errors in your console? To check this, press `f12` in Foundry, and you should see a dev-tools sidebar open. navigate to a section of the window that looks like this: 

![image](https://github.com/jalensailin/bottlecap/assets/72114365/4526180f-f265-4b43-8f43-74189144ae39)

Filter for just the errors section (as above) and screen shot the errors that are there.

Next, could you tell me which version of Foundry you are on and which version of PF1e?

**Comment by RogueCalzone** [comment]
Thanks for the quick reply! It does look like there are some console errors in Foundry, but I believe they're related to other modules.

![Capture - Console Errors](https://github.com/jalensailin/bottlecap/assets/149108430/6bb0848c-e799-4191-80f4-ff0cfc011757)

I'm currently using Version 11 Build 313 of Foundry and version 9.4 of PF1e

**Comment by jalensailin** [comment]
I am having trouble replicating this bug. I am using the same Foundry version and Pathfinder1e version. I also downloaded the resource-tracker module. I am getting no errors and the UI looks as expected:

![image](https://github.com/jalensailin/bottlecap/assets/72114365/bdc6a708-12b0-4e0a-8fa0-7c22d881c007)

I think the next step for you would to turn off your modules and see if that is the source of the error. There is actually a module called "Find The Culprit" which will help you do this in the most efficient way possible (and turn everything back on at the end). I would make a backup of your foundry data before attempting this just in case the process of turning modules on and off creates an issue. If the issue persists with all modules turned off, let me know. If "Find The Culprit" is able to pinpoint the module that is causing the issue, that would be even better.

**Comment by RogueCalzone** [comment]
Thanks for looking into this. I'll do some troubleshooting with Find the Culprit and get back to you with my findings!

**Comment by jalensailin** [comment]
Of course. I appreciate you doing some troubleshooting on your end too! If I could replicate the issue it would be easier lol. I look forward to your findings.

P.S. I just read that Find The Culprit hasn't been updated for v11 but that **it should still work**, you might just see some warnings

**Comment by RogueCalzone** [comment]
Well, Find the Culprit worked as intended! But I'm still having the same issue. I even manually deactivated all my other modules, leaving just 'Bottle Cap!' active, and still experienced the UI bug. I assume it's something else on my end, but I'm not sure what it could be

**Comment by jalensailin** [comment]
That's quite confusing! Are you on the foundry app or via a browser? If you are on a browser, can you try switching browsers and see if the issue persists?

**Comment by jalensailin** [comment]
May also be worth a try to uninstall and reinstall the module

**Comment by RogueCalzone** [comment]
I'm using the foundry app. A fresh install of the module didn't fix the problem, either. I tried giving bottle caps to players to see if increasing the value would change anything, but that also didn't make a difference. Sorry to pose an apparently unsolvable problem! The module is functioning completely as-intended, otherwise

**Comment by jalensailin** [comment]
Would you try opening it in a browser and see if you still get the same problems?

**Comment by RogueCalzone** [comment]
I tested some players joining the server via a browser in various roles, and it still displays the same way.

**Comment by jalensailin** [comment]
would you be able to zip up your world and post it here? i can try to load it and see if its something unique to your world for some reason

**Comment by RogueCalzone** [comment]
[PF1e-Skull-and-Shackles-Bottle-Cap-Debug.zip](https://github.com/jalensailin/bottlecap/files/13189663/PF1e-Skull-and-Shackles-Bottle-Cap-Debug.zip)


[PF1e-Skull-and-Shackles-World-Backup.zip](https://github.com/jalensailin/bottlecap/files/13189670/PF1e-Skull-and-Shackles-World-Backup.zip)

Thanks again for looking into this. I zipped up the world folder in the Data directory as well as the data from the Backup folder, so hopefully that's enough to work with

**Comment by jalensailin** [comment]
Good news! The same issue was occurring in your world for me, and I was able to get to the bottom of it. One of your players has a nickname in their username which is encased in double quotes: `"`. I did not account for this when rendering the html, and the double quotes are being interpreted as though they are part of the code. If you change that user to have single quotes `'` instead of double quotes, it will be fixed. I will also push a fix shortly, so you can wait for that as well :)

**Comment by jalensailin** [comment]
This should be fixed in the latest release, with no action required on your end. Let me know if there are any other issues. Enjoy!

**Comment by RogueCalzone** [comment]
You are a WIZARD! Thanks so much for all of your help and your quick responses

**Comment by jalensailin** [comment]
of course! thanks for bringing the issue to my attention
